### PR TITLE
Generate and upload AppImage for Linux

### PR DESCRIPTION
**Pull request by probonopd**
This PR, when merged, will compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to your GitHub Releases page.

Symphonium

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines
- Decentralized

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

__PLEASE NOTE:__ For this to work, you need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

### CODE REVIEW

**Comment by probonopd** [comment]
An AppImage for testing can be downloaded from:
https://github.com/probonopd/Symphonium/releases/tag/continuous

**Comment by ttdm** [comment]
Thanks ! 

I took a bit of time to check what you were doing since it's mainly stuff I'm not proficient in. 

Seems to me your merge is what I wanted to make it easily available for linux users. 
Thanks again !

**Comment by probonopd** [comment]
Thanks for merging.

https://github.com/ttdm/Symphonium/releases is still missing the file though, so maybe you haven't set up Travis CI yet? You need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool.

**Comment by ttdm** [comment]
Yeah, I saw it and i'm currently adding it ;) 

Should be there in a few minutes

**Pull request merged**
